### ISSUE TITLE
preProduction. RFL + Профиль. from trello

### ISSUE THREAD

**Issue by igofftt** [scientex/keyhabits.ru#47]
https://trello.com/c/BK5I7my2/59-preproduction-rfl

- [x] 1. Регистрация: поля заполнены корректно, но капча не активирована. Нажимаем кнопку, система не реагирует. Логично увидеть сервисное окно об ошибке капчи: http://joxi.ru/J2byvaQu6vjXm6

- [x] 2. Регистрация: поле ввода мейла не позеленеет при правильно введённом мейле пока курсор не будет убран с поля ввода. Логично сменить рамку с красно на зелёную, когда мейл введён корректно и полностью вне зависимости от положения курсора.

- [x] 3. Регистрация: здесь сейчас введён символ кириллицы, система не протестует: http://joxi.ru/xAeEPOWfEZzZAy. Нужно предупредить о некорректном символе и рамку в этом случае окрасить красным. Такое же поведение полей паролей должно быть и на странице "Смена пароля". Полагаю, что не все символы могут быть в пароле, система должна реагировать на запрещённые символы аналогично.

- [x] 4. Страница входа: введённый мейл принят, но пароль не подходит. Не хватает сервисного сообщения о неправильно введённом пароле: http://joxi.ru/a2XDMGoUYgxM2g

- [x] 5. Введённый мейл не зарегистрирован, но система его приняла: http://joxi.ru/brRj7potv4ynr1

- [x] 6. При входе с неверным паролем не хватает сервисного сообщения "Логин и пароль не совпадают". Форма молча подсвечивает пароль красным - этого мало для понимания что происходит.

- [x] 7. При вводе пароля на входе на 7-м символе (из 16) поле пароля радостно зеленеет, как будто я уже ввел верный пароль. Разумеется, войти не получается. Поле должно зеленеть только после введения полного и верного пароля.

- [x] 8. Окно "Смена пароля": неявно (просто подсвечено красным поле) при неверном текущем пароле.Нужно прописать красными буквами над полем характер ошибки.

- [x] 9. Окно "Смена пароля": при неверном текущем пароле и совпадающих новых нажатие на кнопку вызывает возврат на главную страницу сервиса. Должно быть сервисное сообщение об ошибке без смены страницы.

- [x] 10. Страница "Смена пароля": покраснение поля текущего пароля происходит после введения нескольких символов (с задержкой). Так и задумано? Ему логично покраснеть с первого активации и быть красным до совпадения пароля (зелёная рамка).

- [x] 11. Страница "Смена пароля": поле при верном текущем пароле не позеленеет, пока курсор не будет убран с поля текущего пароля. Логично, если оно позеленеет при введении верного пароля вне зависимости от положения курсора.

- [x] 12. "Смена пароля": текущий верно, новый 2 не совпадает с новым 1. Индикация полей отсутствует: http://joxi.ru/MAjJW9aUQ8elAe. Нужно подсветить поля красным, над вторым вывесить сервисное сообщение "пароли не совпадают". При совпадении поля зеленеют.

- [x] 13. "Сброс пароля": поле ввода мейл остаётся красным даже когда мейл введен верный и полностью, пока курсор не уйдет с поля. Нужно сменить рамку на зеленую при введении верного мейла вне зависимости от положения курсора.

- [x] 14. Смена фамилии в профиле: не очевидно, что для сохранения введенной фамилии нужно убрать курсор с поля. Логично сделать сохранение по Enter.

**Comment by igofftt** [comment]
2. ??? браузер не оповещает если значение в инпут было введено с автозаполения, есть вариант как отловить, но нахожу этот метод костылём, пока отложим вопрос

**Comment by igofftt** [comment]
4. !!! в вайбере писал подробно, проверка только на валидность, точная проверка на совпадение происходит а сервере

**Comment by igofftt** [comment]
8. тут всё остановилось на верстке, я просил стили дописать или хотя бы сказать мне, что использовать что бы подсветить ошибки правильно - тишина. @pmenshih @enenkoff @vesnins

**Comment by igofftt** [comment]
10. Задержка в проверке нужна, она всего 0.5секунды, это что бы избежать кучу запросов на сервер.

**Comment by vesnins** [comment]
@igofftt , что нужно отрисовать/сверстать по 8 и 12 пунктам?

**Comment by igofftt** [comment]
@vesnins, надо вывод ошибок в порядок привести. сейчас там просто текст выпадает не стилизованный

**Comment by vesnins** [comment]
@igofftt 
# **Вход/регистрация/смена пароля/сброс пароля**
1. Вход с неправильным паролем: неверный пароль - поле краснеет (зачёт), нажатие кнопки "Войти" - нет сервисного сообщения об ошибке (не зачёт)

2. Вход: поле mail принимает адрес (причём, зеленеет как требовал - после введения последнего символа), сброс пароля (http://joxi.ru/Rmz58VMhPgzkrO) - этот же mail уже не принимает. Явный баг: либо система на входе не распознаёт незарегистрированный mail и светит поле зелёным, либо косяк в сбросе пароля, который mail не принимает. Истина где-то рядом.

3. Регистрация не отдаёт сервисного сообщения. "Успешно... Проверьте... Подтвердите... Бла-бла".

4. Вход: ввожу mail автокомплитом. Поле красное, пока не кликнуть мимо поля. 

5. Смена пароля из профиля: к чему эти точки? http://joxi.ru/Y2L4nEoCj44G26 Их 4, они путают, поле оставь пустым. В идеале там звездочки по количеству совпадающие с количеством символов старого пароля. но это даже звучит заморочено.

6. Смена пароля: пароль не совпадает, но без усилий не увидеть http://joxi.ru/12M4XNoCBNz0mJ. Поля бы красными сделать в этом случае, а при совпадении новых паролей окрашивать оба поля в зелёный. Новые пароли короче 6 символов и с кириллицей тоже нужно выделять красной рамкой и красным шрифтом.

7. Мы не можем обойтись без входа при смене пароля? Чтобы оставаться в личных данных?

**Comment by pmenshih** [comment]
> 7. Мы не можем обойтись без входа при смене пароля? Чтобы оставаться в личных данных?

Это мой косяк. Тоже самое касается смены мыла и регистрации. Помечено [тут](https://trello.com/c/BK5I7my2/59-preproduction-rfl), сразу после завершения админки будет исправлено.

**Comment by igofftt** [comment]
2. пункт починил
![2.](http://dl4.joxi.net/drive/2017/03/07/0017/3396/1174852/52/ece50d54f4.jpg "2.")
5 - убрал точки

**Comment by vesnins** [comment]
@igofftt, когда починим остальное?

**Comment by igofftt** [comment]
@vesnins там остальное не от меня зависит. дизайн(ошибки для смены пароля) и сервер остался @pmenshih должен быть обо всём в курсе.
