### ISSUE TITLE
Анкетирование (https://dev.keyhabits.ru/form)

### ISSUE THREAD

**Issue by vesnins** [scientex/keyhabits.ru#51]
- [ ] 1. Попытка нажать кнопку "Далее" не выбрав ответа не вызывает сообщения о необходимости выбрать ответ. 
1. Либо высвечиваем стандартное "Ответ обязателен"
2. Либо кнопка "Далее" неактивна до выбора
3. Либо и то, и другое (п.1 и п.2)

- [ ]  2. Не написал ответ в текстовом поле открытого вопроса. Кнопка "Далее" перекинула на следующий вопрос. Эти вопросы необязательны? Если обязательны, то см. ошибку №1.

- [x] 3. Незаметно, что я оценил этот фактор на 5: http://joxi.ru/nAyQ7MgfPxyaAZ. Лучше подсветить квадрат заливкой отличного цвета ( @enenkoff )

**Comment by pmenshih** [comment]
Касательно п. 1 и 2: любой вопрос у нас может быть необязательным, при этом мы не хотим явно обозначать эту особенность, чтобы люди, по возможности, заполняли всё.

Поэтому пока так.
